/* 小狗记事本：可离线运行的交互原型。演示日期与 AI / 语音数据均为模拟。 */

(function(){
  'use strict';
  const root=document.getElementById('puppy-notebook-prototype');
  const phone=root.querySelector('#pn-phone'), main=root.querySelector('#pn-main'), overlay=root.querySelector('#pn-overlay');
  const assets=window.puppyNotebookAssets;
  function dateString(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
  const TODAY=dateString(new Date());
  function dateParts(s){const p=s.split('-');return {y:+p[0],m:+p[1],d:+p[2]};}
  function weekdayCN(s){return '日一二三四五六'.charAt(new Date(s+'T12:00:00').getDay());}
  function mdLabel(s){const p=dateParts(s);return p.m+'月'+p.d+'日';}
  function fullDateLabel(s){return mdLabel(s)+' · 星期'+weekdayCN(s);}
  function futureDate(days){const d=new Date(TODAY+'T12:00:00');d.setDate(d.getDate()+days);return dateString(d);}
  function nextWeekday(target){const base=new Date(TODAY+'T12:00:00');let diff=(target-base.getDay()+7)%7;if(!diff)diff=7;base.setDate(base.getDate()+diff);return dateString(base);}
  const petNames={white:'小白',golden:'小鸡毛'};
  const products={
    food:{name:'香香狗粮',price:6,desc:'饱腹 +25 · 一次食用',icon:'soup',type:'food'},
    snack:{name:'小骨头饼干',price:10,desc:'饱腹 +12 · 心情 +10',icon:'cookie',type:'food'},
    toy:{name:'软软咬咬玩具',price:40,desc:'永久拥有 · 玩耍心情 +16',icon:'bone',type:'toy'},
    rug:{name:'奶油小毯子',price:30,desc:'永久拥有 · 给小窝换一块暖毯',icon:'lamp-desk',type:'decor'},
    flower:{name:'窗边小花',price:25,desc:'永久拥有 · 装点小窝',icon:'flower-2',type:'decor'}
  };
  function seed(){return {version:2,rev:0,page:'notes',pet:'golden',coins:30,noteFilter:'all',taskFilter:'today',calendarDate:TODAY,notes:[
    {id:'n1',title:'和豆豆散步的下午',body:'阳光刚刚好，今天也有小狗陪着我。',date:TODAY,mood:'开心',tag:'生活',photo:true,audio:false,diary:true,favorite:false,rewarded:true},
    {id:'n2',title:'突然想到的小灵感',body:'想把小狗的日常画成贴纸，应该会很可爱！',date:TODAY,mood:'平静',tag:'灵感',photo:false,audio:true,diary:false,favorite:false,rewarded:true}
  ],tasks:[
    {id:'t1',title:'带豆豆去洗澡',date:TODAY,time:'14:00',done:false,rewarded:false},
    {id:'t2',title:'买狗粮',date:TODAY,time:'',done:false,rewarded:false},
    {id:'t3',title:'整理桌面',date:TODAY,time:'',done:true,rewarded:true}
  ],anniversaries:[{id:'a1',title:'豆豆生日',date:futureDate(11),annual:true}],pets:{white:{mood:88,satiety:72,energy:85},golden:{mood:88,satiety:72,energy:85}},
  bag:{food:0,snack:0,toy:false,rug:false,flower:false},decor:{white:'',golden:''},reward:{date:TODAY,notes:0,tasks:0},round:{note:false,task:false,buy:false,feed:false},roundCelebrated:false,
  chats:{white:[{role:'dog',text:'我是小白。想做的小事，我们一件件来。'}],golden:[{role:'dog',text:'我是小鸡毛。今天有什么想记下来的？'}]},draft:null,ledger:[{text:'欢迎来到小窝',amount:30}],freeFood:false};}
  let state=seed(), sheet=null, returnSheet=null, draftTasks=[], shopTab='food', petPose='defaultQuiet', petPhrase='今天想一起做什么？', poseTimer=null,toastTimer=null,recordTimer=null,recordSeconds=0,searchQuery='',formError='',exportSource='';
  window.puppyNotebookStore.read(function(saved){
    if(saved && saved.version===2){state=Object.assign(seed(),saved);normalizeDates(state);}
    render();
  });
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function icon(name){return '<i data-lucide="'+name+'" aria-hidden="true"></i>';}
  function button(label,action,extra,cls){return '<button type="button" class="'+(cls||'pn-secondary')+' cursor-interaction" data-action="'+action+'" '+(extra||'')+'>'+label+'</button>';}
  function name(){return petNames[state.pet];}
  function assetFor(character,pose){return assets.find(function(a){return a.character===character && a.state===pose;}) || assets.find(function(a){return a.character===character && a.state==='default';});}
  function art(asset,width,label){if(!asset)return '';const b=asset.bbox,bw=b[2]-b[0],bh=b[3]-b[1],s=width/bw;return '<span class="pn-dog" role="img" aria-label="'+esc(label||'小狗')+'" style="width:'+width+'px;height:'+(bh*s).toFixed(2)+'px"><img alt="" src="'+asset.dataUrl+'" style="width:'+(asset.width*s).toFixed(2)+'px;height:'+(asset.height*s).toFixed(2)+'px;left:'+(-b[0]*s).toFixed(2)+'px;top:'+(-b[1]*s).toFixed(2)+'px"></span>';}
  function dog(character,pose,width){return art(assetFor(character,pose),width,petNames[character]);}
  function photo(width){return art(assets.find(function(a){return a.character==='scene';}),width,'虚构生活照片：小白和小鸡毛野餐');}
  function wave(){return '<span class="pn-wave">'+[8,14,20,11,17,7,16,12,20,8,15,11,17,8,12,19,9,16,7,12].map(function(h){return '<b style="height:'+h+'px"></b>';}).join('')+'</span>';}
  function initializeIcons(){if(globalThis.lucide){lucide.createIcons({attrs:{width:18,height:18,'stroke-width':1.8}});}}
  function save(){state.rev++;window.puppyNotebookStore.write(state,function(ok){if(!ok){toast('浏览器暂时无法保存进度，当前操作仍可体验。');}});}
  function normalizeDates(s){const old='2026-10-07';s.notes.forEach(function(n){if(n.date===old)n.date=TODAY;});s.tasks.forEach(function(t){if(t.date===old)t.date=TODAY;});s.anniversaries.forEach(function(a){if(a.date==='2026-10-19')a.date=futureDate(11);});if(s.calendarDate===old)s.calendarDate=TODAY;if(s.reward&&s.reward.date===old)s.reward.date=TODAY;}
  function toast(text){const el=root.querySelector('#pn-toast');clearTimeout(toastTimer);el.textContent=text;el.hidden=false;root.querySelector('#pn-live').textContent=text;toastTimer=setTimeout(function(){el.hidden=true;},2800);}
  function award(amount,text){state.coins+=amount;state.ledger.push({text:text,amount:amount});state.ledger=state.ledger.slice(-10);}
  function roundCount(){return Object.values(state.round).filter(Boolean).length;}
  function segment(items,active,action){return '<div class="pn-segment">'+items.map(function(v){return button(esc(v[1]),action,'data-value="'+v[0]+'" aria-pressed="'+(active===v[0])+'"','');}).join('')+'</div>';}
  function companion(character,text){return '<div class="pn-companion">'+button(dog(character,'defaultQuiet',62),'companion','data-pet="'+character+'"','pn-pet-button')+'<span class="pn-bubble">'+esc(text)+'</span></div>';}
  function noteCard(n){return '<button type="button" class="pn-note cursor-interaction" data-action="view-note" data-id="'+n.id+'" aria-label="查看记录：'+esc(n.title)+'"><div class="pn-note-head"><h3>'+esc(n.title||'无标题记录')+'</h3>'+icon('ellipsis')+'</div><p>'+esc(n.body.length>50?n.body.slice(0,50)+'…':n.body)+'</p>'+(n.photo?'<div class="pn-photo">'+photo(165)+'<span class="pn-photo-label">示例照片</span></div>':'')+(n.audio?'<div class="pn-audio">'+icon('circle-play')+wave()+'<span>模拟语音 00:12</span></div>':'')+'<div class="pn-note-meta"><span>'+icon(n.diary?'book-open':'lightbulb')+esc(n.tag||'生活')+' · '+esc(n.date.slice(5).replace('-','/'))+'</span><span>'+icon(n.favorite?'heart-handshake':'heart')+esc(n.mood)+'</span></div></button>';}
  function notesPage(){const list=state.notes.filter(function(n){return state.noteFilter==='all'||state.noteFilter==='diary'&&n.diary||state.noteFilter==='favorite'&&n.favorite;});
    return '<div class="pn-page-tools"><h2>随手记</h2><div>'+button(icon('search'),'search','aria-label="搜索记录"','pn-icon')+button(icon('calendar-days'),'calendar','aria-label="日历回看"','pn-icon')+'</div></div>'+segment([['all','全部'],['diary','日记'],['favorite','收藏']],state.noteFilter,'note-filter')+'<div class="pn-date-row"><span>'+fullDateLabel(TODAY)+'</span><span class="pn-mood">'+icon('smile')+'今天很开心</span></div>'+(list.length?list.slice(0,3).map(noteCard).join(''):'<div class="pn-empty">这里还没有记录。<br>记下今天的一件小事吧。</div>')+companion('golden','我陪你慢慢记。')+button(icon('plus')+'记一笔','new-note','','pn-primary');}
  function dateLabel(date){if(!date)return '未安排';if(date===TODAY)return '今天';return date.slice(5).replace('-','月')+'日';}
  function taskRow(t){return '<div class="pn-task '+(t.done?'done':'')+'"><input type="checkbox" data-task="'+t.id+'" '+(t.done?'checked':'')+' aria-label="完成任务：'+esc(t.title)+'"><button type="button" class="cursor-interaction" data-action="edit-task" data-id="'+t.id+'"><strong>'+esc(t.title)+'</strong><small>'+icon(t.done?'circle-check':'clock-3')+esc(t.done?'已完成':dateLabel(t.date)+(t.time?' '+t.time:''))+'</small></button>'+icon('ellipsis')+'</div>';}
  function countdown(a){const base=new Date(TODAY+'T12:00:00'),target=new Date(a.date+'T12:00:00');if(a.annual){target.setFullYear(base.getFullYear());if(target<base)target.setFullYear(base.getFullYear()+1);}return Math.ceil((target-base)/86400000);}
  function countdownText(a){const days=countdown(a);return days===0?'就是今天':days>0?'还有 '+days+' 天':'已过去 '+Math.abs(days)+' 天';}
  function tasksPage(){const a=state.anniversaries[0], list=state.tasks.filter(function(t){return state.taskFilter==='all'||state.taskFilter==='done'&&t.done||state.taskFilter==='today'&&t.date===TODAY;});const todays=state.tasks.filter(function(t){return t.date===TODAY;}),done=todays.filter(function(t){return t.done;}).length;
    return '<div class="pn-page-tools"><h2>待办</h2>'+button(icon('plus'),'new-task','aria-label="添加待办"','pn-icon')+'</div><button type="button" class="pn-anniversary cursor-interaction" data-action="anniversaries">'+icon('cake')+'<div><strong>'+esc(a.title)+'</strong><div class="pn-countdown">'+(countdown(a)===0?'就是今天':'还有 <b>'+countdown(a)+'</b> 天')+'</div><small>'+dateLabel(a.date)+'</small></div><span class="pn-link">全部纪念日 ›</span></button>'+segment([['today','今天'],['all','全部'],['done','已完成']],state.taskFilter,'task-filter')+'<div class="pn-date-row"><span>'+fullDateLabel(TODAY)+'</span><span style="font-size:11px;color:var(--pn-muted);font-weight:400">今天完成 '+done+' / '+todays.length+' 件小事</span></div><div class="pn-task-card">'+(list.length?list.map(taskRow).join(''):'<div class="pn-empty">小目标都在这里，慢慢来。</div>')+'</div><div class="pn-reward-note">'+icon('paw-print')+'完成小目标，收获狗狗币</div>'+companion('white','慢慢来，我陪你。')+button(icon('plus')+'添加待办','new-task','','pn-primary');}
  function room(){const d=state.decor[state.pet], other=state.pet==='white'?'golden':'white';return '<div class="pn-room" data-layer="小狗房间"><div class="pn-room-label">'+esc(name())+'的小窝'+icon('paw-print')+'</div><div class="pn-room-window"><span class="pn-window-cloud"></span><span class="pn-window-line horizontal"></span><span class="pn-window-line vertical"></span></div><div class="pn-room-floor"></div><div class="pn-room-rug" style="background:'+(d==='rug'?'#f3d392':'#c0cda3')+'"></div><div class="pn-pot">'+icon('sprout')+'</div><div class="pn-wall-card">'+icon('heart')+'</div><div class="pn-shelf"></div><div class="pn-frame">'+dog('white','defaultQuiet',18)+dog('golden','defaultQuiet',18)+'</div><div class="pn-room-bed"></div><div class="pn-room-white">'+dog(other,'sleep',68)+'</div><div class="pn-room-bed-front"></div>'+button(dog(state.pet,petPose,petPose==='sleep'?105:110),'pet','','pn-room-main'+(petPose!=='defaultQuiet'?' pn-wiggle':''))+'<div class="pn-room-speech">'+esc(petPhrase)+'</div><div class="pn-room-ball">'+icon('volleyball')+'</div>'+(d==='flower'?'<div class="pn-decoration">'+icon('flower-2')+'</div>':'')+'</div>';}
  function stats(){const p=state.pets[state.pet];return '<div class="pn-stats">'+[['mood','心情','heart','#eea69c'],['satiety','饱腹','soup','#edba5e'],['energy','精力','sparkles','#a2bb91']].map(function(x){return '<div class="pn-stat"><div class="pn-stat-top">'+icon(x[2])+x[1]+'</div><strong>'+p[x[0]]+'</strong><div class="pn-meter" role="progressbar" aria-label="'+x[1]+'" aria-valuenow="'+p[x[0]]+'" aria-valuemin="0" aria-valuemax="100"><span style="width:'+p[x[0]]+'%;background:'+x[3]+'"></span></div></div>';}).join('')+'</div>';}
  function homePage(){return '<div class="pn-pet-tabs">'+[['white','小白'],['golden','小鸡毛']].map(function(x){return button(dog(x[0],'defaultQuiet',22)+x[1],'select-pet','data-pet="'+x[0]+'" aria-pressed="'+(state.pet===x[0])+'"','');}).join('')+'</div>'+room()+stats()+'<div class="pn-interactions">'+[['pet','摸摸','hand'],['feed-menu','喂食','soup'],['play','玩耍','volleyball'],['rest','休息','moon']].map(function(v){return button(icon(v[2])+v[1],v[0],'','');}).join('')+'</div>'+button(icon('message-circle')+'和小狗聊聊','chat','','pn-primary')+'<div class="pn-shortcuts">'+button(icon('store')+'商店','shop')+button(icon('backpack')+'背包','bag')+button(icon('paintbrush')+'布置','decorate')+'</div>';}
  function render(){root.dataset.page=state.page;root.dataset.coins=state.coins;root.dataset.pet=state.pet;root.dataset.state=JSON.stringify({coins:state.coins,pets:state.pets,bag:state.bag,round:state.round,notes:state.notes.length,tasks:state.tasks});
    root.querySelector('#pn-coins').textContent=state.coins;root.querySelector('#pn-subtitle').textContent=state.page==='notes'?'把生活的小事，慢慢记下来':state.page==='tasks'?'把小目标，一件件完成':'今天也有小狗陪你';
    root.querySelector('#pn-round-count').textContent=roundCount()+' / 4';root.querySelector('#pn-round-dots').innerHTML='<span class="pn-round-dots">'+Object.values(state.round).map(function(v){return '<span class="pn-dot '+(v?'on':'')+'"></span>';}).join('')+'</span>';
    root.querySelectorAll('.pn-nav button').forEach(function(b){if(b.dataset.page===state.page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
    main.innerHTML=state.page==='notes'?notesPage():state.page==='tasks'?tasksPage():homePage();renderSheet();initializeIcons();
  }
  function sheetHeader(title){return '<div class="pn-sheet-head"><h2 id="pn-sheet-heading">'+esc(title)+'</h2>'+button(icon('x'),'close-sheet','aria-label="关闭"','pn-icon')+'</div>';}
  function field(label,name,value,type){return '<label class="pn-field">'+label+'<input name="'+name+'" type="'+(type||'text')+'" value="'+esc(value)+'" '+(type==='text'||!type?'maxlength="80"':'')+'></label>';}
  function openSheet(kind,id){sheet={kind:kind,id:id};formError='';renderSheet();initializeIcons();}
  function closeSheet(){if(recordTimer){clearInterval(recordTimer);recordTimer=null;if(state.draft){state.draft.recording=false;state.draft.audio=true;save();}}if(returnSheet){sheet=returnSheet;returnSheet=null;}else sheet=null;formError='';renderSheet();initializeIcons();}
  function draft(){if(!state.draft)state.draft={id:null,title:'',body:'',date:TODAY,mood:'开心',diary:false,photo:false,audio:false,recording:false};return state.draft;}
  function editorSheet(){const d=draft();return sheetHeader(d.id?'编辑这页':'记一笔')+'<form id="pn-note-form">'+field('标题，可不填','title',d.title)+ '<label class="pn-field">今天想记下什么？<textarea name="body" maxlength="500" placeholder="周六带豆豆去洗澡，顺便买狗粮。">'+esc(d.body)+'</textarea></label><div class="pn-field-row">'+field('记录日期','date',d.date,'date')+'<label class="pn-field">心情<select name="mood">'+['开心','平静','有点累','期待'].map(function(v){return '<option '+(d.mood===v?'selected':'')+'>'+v+'</option>';}).join('')+'</select></label></div><label class="pn-check-label"><input name="diary" type="checkbox" '+(d.diary?'checked':'')+'>写为今天的日记</label><div class="pn-editor-tools">'+button(icon('image')+(d.photo?'移除照片':'贴示例照片'),'toggle-photo')+button(icon('mic')+(d.recording?'停止录音':'模拟录音'),'voice')+'</div>'+(d.photo?'<div class="pn-preview-photo">'+photo(115)+'</div>':'')+(d.audio||d.recording?'<div class="pn-audio">'+icon(d.recording?'circle-stop':'circle-play')+wave()+'<span id="pn-recordtime">'+(d.recording?'录制中 '+recordSeconds+'秒':'演示语音已保留')+'</span>'+(!d.recording?button('回听','audio-play','','pn-text-button'):'')+'</div>':'')+'<div class="pn-row">'+button(icon('sparkles')+'演示 AI 整理','extract')+'<span class="pn-hint">草稿自动保留</span></div>'+(formError?'<p class="pn-error" role="alert">'+esc(formError)+'</p>':'')+'<button type="button" data-action="submit-form" class="pn-primary cursor-interaction">'+icon('check')+'收好这页</button></form>';}
  function noteDetail(){const n=state.notes.find(function(n){return n.id===sheet.id;});if(!n)return sheetHeader('记录')+'<p class="pn-empty">这条记录已移走。</p>';return sheetHeader(n.title)+'<p class="pn-hint">'+esc(n.date)+' · '+esc(n.mood)+' · '+(n.diary?'日记':'随手记')+'</p><p style="font-size:14px;line-height:1.7;overflow-wrap:anywhere">'+esc(n.body)+'</p>'+(n.photo?'<div class="pn-preview-photo">'+photo(145)+'</div>':'')+(n.audio?button(icon('play')+'回听模拟语音','audio-play'):'')+'<div class="pn-actions">'+button(icon('pencil')+'编辑','edit-note','data-id="'+n.id+'"')+button(icon('heart')+(n.favorite?'取消收藏':'收藏'),'favorite','data-id="'+n.id+'"')+'</div>'+button(icon('sparkles')+'提取待办草稿','extract','data-id="'+n.id+'"')+'<p class="pn-hint">演示整理会先展示草稿，确认后才加入待办。</p>';}
  function taskSheet(){const t=state.tasks.find(function(t){return t.id===sheet.id;})||{title:'',date:TODAY,time:''};return sheetHeader(sheet.id?'编辑小目标':'添加小目标')+'<form id="pn-task-form">'+field('要做的小事','title',t.title)+field('日期，可留空','date',t.date,'date')+field('时间，可留空','time',t.time,'time')+(formError?'<p class="pn-error" role="alert">'+esc(formError)+'</p>':'')+'<button type="button" data-action="submit-form" class="pn-primary cursor-interaction">'+icon('check')+'保存待办</button></form>';}
  function extractionSheet(){return sheetHeader('小鸡毛整理好了')+'<p class="pn-hint">演示 AI · 请确认具体日期再加入待办。</p><form id="pn-extract-form">'+draftTasks.map(function(t,i){return '<div class="pn-product"><input type="checkbox" name="pick'+i+'" checked aria-label="加入：'+esc(t.title)+'"><div>'+field('小目标','title'+i,t.title)+field('日期','date'+i,t.date,'date')+'</div></div>';}).join('')+'<button type="button" data-action="submit-form" class="pn-primary cursor-interaction">'+icon('list-checks')+'确认加入待办</button></form>';}
  function shopSheet(){return sheetHeader('小窝商店')+'<div class="pn-reward-note">'+icon('paw-print')+'狗狗币余额 '+state.coins+'</div>'+segment([['food','食物'],['toy','玩具'],['decor','装饰']],shopTab,'shop-tab')+Object.keys(products).filter(function(k){return products[k].type===shopTab;}).map(function(k){const p=products[k],owned=p.type!=='food'&&state.bag[k];return '<div class="pn-product">'+icon(p.icon)+'<div><strong>'+p.name+'</strong><p>'+p.desc+'</p><p>'+p.price+' 狗狗币</p></div>'+button(owned?'已拥有':'购买','buy','data-key="'+k+'" '+(owned?'disabled':''))+'</div>';}).join('')+(formError?'<p class="pn-error" role="alert">'+esc(formError)+'</p>':'')+'<p class="pn-hint">购买后进入背包；永久物品可以反复使用。</p>';}
  function bagSheet(feeding){return sheetHeader(feeding?'给'+name()+'喂点好吃的':'小狗背包')+['food','snack'].map(function(k){const p=products[k];return '<div class="pn-product">'+icon(p.icon)+'<div><strong>'+p.name+'</strong><p>还有 '+state.bag[k]+' 份</p></div>'+button('喂给'+name(),'feed','data-key="'+k+'" '+(!state.bag[k]?'disabled':''))+'</div>';}).join('')+'<div class="pn-product">'+icon('volleyball')+'<div><strong>基础小球</strong><p>永久拥有 · 随时一起玩</p></div>'+button('玩一会','play')+'</div>'+(state.bag.toy?'<div class="pn-product">'+icon('bone')+'<div><strong>软软咬咬玩具</strong><p>永久拥有</p></div>'+button('玩一会','play','data-toy="toy"')+'</div>':'')+'<div class="pn-actions">'+button(icon('store')+'去商店','shop')+button('领一份口粮','free-food',state.freeFood?'disabled':'')+'</div>'+(formError?'<p class="pn-error" role="alert">'+esc(formError)+'</p>':'');}
  function decorSheet(){return sheetHeader('布置'+name()+'的小窝')+'<p class="pn-hint">选择已拥有的装饰，两只小狗可以分别布置。</p>'+['rug','flower'].map(function(k){return '<div class="pn-product">'+icon(products[k].icon)+'<div><strong>'+products[k].name+'</strong><p>'+(state.bag[k]?'已拥有':'还没有，去商店看看')+'</p></div>'+button(state.decor[state.pet]===k?'已放好':'放进小窝','equip','data-key="'+k+'" '+(!state.bag[k]?'disabled':''))+'</div>';}).join('')+'<div class="pn-actions">'+button('恢复基础布置','equip','data-key=""')+button(icon('store')+'去商店','shop')+'</div>';}
  function chatSheet(){return sheetHeader('和'+name()+'聊聊')+'<div class="pn-reward-note">'+icon('sparkles')+'角色演示回复</div><div class="pn-chat-log">'+state.chats[state.pet].slice(-3).map(function(m){return '<div class="pn-chat-message '+(m.role==='user'?'user':'')+'">'+(m.role==='dog'?dog(state.pet,'defaultQuiet',26):'')+'<p>'+esc(m.text)+'</p></div>';}).join('')+'</div><div class="pn-chat-presets">'+button('今天有点累','chat-preset','data-text="今天有点累"')+button('周六洗澡、买狗粮','chat-preset','data-text="周六带豆豆去洗澡，顺便买狗粮。"')+'</div><form id="pn-chat-form" class="pn-chat-form"><input name="message" maxlength="160" aria-label="和小狗说句话" placeholder="说说今天的小事…"><button type="button" data-action="submit-form" class="pn-secondary cursor-interaction" aria-label="发送">'+icon('send')+'</button></form><div style="margin-top:10px">'+button(icon('list-checks')+'整理成待办','extract-chat')+'</div>';}
  function roundSheet(){const steps=[['note','收好一条新记录','notes'],['task','完成一个小目标','tasks'],['buy','在商店买一份食物','home'],['feed','给小狗喂一次食物','home']];return sheetHeader(roundCount()===4?'今天的小目标完成啦':'今日陪伴小目标')+'<div class="pn-celebrate">'+dog('white',roundCount()===4?'pet':'defaultQuiet',72)+dog('golden',roundCount()===4?'pet':'defaultQuiet',80)+'</div>'+steps.map(function(s){return '<div class="pn-info-row">'+icon(state.round[s[0]]?'circle-check':'circle')+'<span>'+s[1]+'</span>'+(state.round[s[0]]?'<small>完成</small>':button('去看看','round-go','data-step="'+s[0]+'" data-page="'+s[2]+'"'))+'</div>';}).join('')+(roundCount()===4?'<div class="pn-success">你记录了生活，也照顾了小狗。<br>获得「今天很棒」小爪印贴纸！</div>':'')+button('继续慢慢记','close-sheet','','pn-primary');}
  function anniversarySheet(){return sheetHeader('值得记住的日子')+state.anniversaries.map(function(a){return '<div class="pn-product">'+icon('cake')+'<div><strong>'+esc(a.title)+'</strong><p>'+esc(a.date)+' · '+(a.annual?'每年重复':'一次性')+'</p><p>'+countdownText(a)+'</p></div>'+button('写一页','anniversary-note','data-title="'+esc(a.title)+'"')+'</div>';}).join('')+button(icon('plus')+'添加纪念日','new-anniversary','','pn-primary');}
  function calendarSheet(){const p=dateParts(TODAY),year=p.y,month=p.m,leading=new Date(year,month-1,1).getDay(),days=new Date(year,month,0).getDate(),prefix=year+'-'+String(month).padStart(2,'0')+'-';return sheetHeader(year+'年'+month+'月')+'<div class="pn-calendar">'+['日','一','二','三','四','五','六'].map(function(v){return '<span style="text-align:center;font-size:11px;color:var(--pn-muted)">'+v+'</span>';}).join('')+Array(leading).fill('<span></span>').join('')+Array.from({length:days},function(_,i){const d=prefix+String(i+1).padStart(2,'0'),mark=state.notes.some(function(n){return n.date===d;});return button(String(i+1)+(mark?'<span class="pn-calendar-mark"></span>':''),'calendar-day','data-date="'+d+'" aria-pressed="'+(state.calendarDate===d)+'"','');}).join('')+'</div><p class="pn-hint">'+esc(state.calendarDate)+' 的记录</p>'+state.notes.filter(function(n){return n.date===state.calendarDate;}).map(function(n){return button(icon('notebook')+esc(n.title),'view-note','data-id="'+n.id+'"');}).join('');}
  function searchResults(){const notes=state.notes.filter(function(n){return (n.title+n.body).includes(searchQuery);});return notes.length?notes.map(function(n){return '<div class="pn-info-row">'+icon('notebook')+'<span>'+esc(n.title)+'</span>'+button('查看','view-note','data-id="'+n.id+'"')+'</div>';}).join(''):'<p class="pn-empty">没有找到这条小事。</p>';}
  function settingsSheet(){return sheetHeader('手帐设置')+'<div class="pn-info-row">'+icon('shield-check')+'<span>单人体验 · 无需登录</span></div><div class="pn-info-row">'+icon('sparkles')+'<span>AI 与语音使用虚构数据演示</span></div><div class="pn-info-row">'+icon('save')+'<span>进度保存在本机（IndexedDB）</span></div><div class="pn-actions">'+button(icon('download')+'导出全部数据','export-json')+button(icon('upload')+'导入数据','import-json')+'</div><p class="pn-hint">换设备或担心数据丢失时，先导出 JSON 备份，再在另一台设备导入。</p><div class="pn-actions">'+button(icon('image')+'导出当前界面','export-svg')+button(icon('rotate-ccw')+'重置演示','reset')+'</div><p class="pn-hint">重置只恢复示例记录、小狗状态和狗狗币。</p>'+'<input type="file" id="pn-import-file" accept="application/json,.json" hidden>';}
  function exportJSON(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='小狗记事本-备份-'+TODAY+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);toast('数据已导出，请妥善保存备份文件。');}
  function importJSON(file){const reader=new FileReader();reader.onload=function(){try{const data=JSON.parse(reader.result);if(!data||data.version!==2){toast('无法导入：文件格式不兼容。');return;}state=Object.assign(seed(),data);normalizeDates(state);save();sheet=null;returnSheet=null;render();toast('数据已导入。');}catch(_){toast('无法导入：文件读取失败。');}};reader.readAsText(file);}
  function renderSheet(){if(!sheet){overlay.hidden=true;overlay.innerHTML='';main.style.minHeight='';return;}let content='';
    if(sheet.kind==='editor')content=editorSheet();else if(sheet.kind==='note')content=noteDetail();else if(sheet.kind==='task')content=taskSheet();else if(sheet.kind==='extract')content=extractionSheet();else if(sheet.kind==='shop')content=shopSheet();else if(sheet.kind==='bag'||sheet.kind==='feed')content=bagSheet(sheet.kind==='feed');else if(sheet.kind==='decorate')content=decorSheet();else if(sheet.kind==='chat')content=chatSheet();else if(sheet.kind==='round')content=roundSheet();else if(sheet.kind==='anniversaries')content=anniversarySheet();else if(sheet.kind==='new-anniversary')content=sheetHeader('添加纪念日')+'<form id="pn-anniversary-form">'+field('纪念日名称','title','')+field('日期','date',TODAY,'date')+'<label class="pn-check-label"><input type="checkbox" name="annual" checked>每年重复</label>'+(formError?'<p class="pn-error" role="alert">'+esc(formError)+'</p>':'')+'<button type="button" data-action="submit-form" class="pn-primary cursor-interaction">保存纪念日</button></form>';else if(sheet.kind==='calendar')content=calendarSheet();else if(sheet.kind==='search')content=sheetHeader('找一件小事')+'<label class="pn-field">搜索记录<input id="pn-search-input" type="search" value="'+esc(searchQuery)+'" aria-label="搜索关键词" placeholder="输入标题或内容"></label><div id="pn-search-results">'+searchResults()+'</div>';else if(sheet.kind==='wallet')content=sheetHeader('狗狗币小账本')+'<div class="pn-success">目前有 '+state.coins+' 狗狗币</div>'+state.ledger.slice().reverse().map(function(l){return '<div class="pn-info-row"><span>'+esc(l.text)+'</span><strong>'+(l.amount>0?'+':'')+l.amount+'</strong></div>';}).join('');else if(sheet.kind==='settings')content=settingsSheet();
    if(sheet.kind==='export')content=sheetHeader('导出这页')+'<p class="pn-hint">SVG 界面图层可以导入 Figma 编辑。互动玩法继续在这里体验。</p><a id="pn-export-file" class="pn-primary cursor-interaction" style="text-decoration:none" download="'+({notes:'随手记',tasks:'待办',home:'小窝'}[state.page])+'.svg" href="data:image/svg+xml;charset=utf-8,'+encodeURIComponent(exportSource)+'">'+icon('download')+'保存这页 SVG</a>';
    overlay.hidden=false;overlay.innerHTML='<section class="pn-sheet" role="dialog" aria-modal="true" aria-labelledby="pn-sheet-heading">'+content+'</section>';initializeIcons();
    const sh=overlay.querySelector('.pn-sheet');if(sh && sh.offsetHeight+65>phone.offsetHeight){main.style.minHeight=(sh.offsetHeight+65-205)+'px';}else main.style.minHeight='';
  }
  function setPose(pose,phrase){clearTimeout(poseTimer);petPose=pose;petPhrase=phrase;poseTimer=setTimeout(function(){petPose='defaultQuiet';petPhrase='今天想一起做什么？';if(state.page==='home'&&!sheet){main.innerHTML=homePage();initializeIcons();}},1800);}
  function interact(action,key){const p=state.pets[state.pet];
    if(action==='pet'){p.mood=Math.min(100,p.mood+5);setPose('pet','蹭蹭你，今天也很喜欢你。');toast(name()+'心情 +5');}
    else if(action==='play'){if(p.energy<10){toast(name()+'想休息一下，先睡一会吧。');return;}p.mood=Math.min(100,p.mood+(key==='toy'?16:12));p.energy=Math.max(0,p.energy-12);setPose('play','追到小球啦！');toast(name()+'心情上升，精力 -12');}
    else if(action==='rest'){p.energy=Math.min(100,p.energy+20);setPose('sleep','呼噜……休息一下。');toast(name()+'精力 +20');}
    else if(action==='feed'){if(!state.bag[key]){formError='背包还没有这份食物，去商店看看吧。';renderSheet();return;}if(p.satiety===100){formError=name()+'已经吃饱啦，留着下次吃。';renderSheet();return;}state.bag[key]--;p.satiety=Math.min(100,p.satiety+(key==='snack'?12:25));p.mood=Math.min(100,p.mood+(key==='snack'?10:3));state.round.feed=true;sheet=null;setPose('feed','香香的，谢谢你！');toast(name()+'吃饱了一点，背包食物 -1');}
    save();render();if(roundCount()===4&&!state.roundCelebrated){state.roundCelebrated=true;save();setTimeout(function(){openSheet('round');},400);}
  }
  function extract(text){const titles=/洗澡|狗粮/.test(text)?['带豆豆去洗澡','买狗粮']:['整理今天的小灵感','给自己留一点休息时间'];draftTasks=titles.map(function(t){return {title:t,date:/周六/.test(text)?nextWeekday(6):TODAY};});returnSheet=sheet;openSheet('extract');}
  function chatSend(text){text=text.trim();if(!text)return;const reply=/洗澡|狗粮/.test(text)?'听到了！我可以帮你拆成“带豆豆洗澡”和“买狗粮”，先确认周六是'+mdLabel(nextWeekday(6))+'。':/累|难过/.test(text)?'今天已经很努力了。先喝点水，给自己留十分钟，慢慢来就好。':'这件小事我记住啦。想把它写进手帐，还是先和我聊一会？';
    state.chats[state.pet].push({role:'user',text:text},{role:'dog',text:reply});state.chats[state.pet]=state.chats[state.pet].slice(-6);save();renderSheet();}
  root.addEventListener('input',function(e){if(e.target.id==='pn-search-input'){searchQuery=e.target.value;root.querySelector('#pn-search-results').innerHTML=searchResults();initializeIcons();return;}if(sheet&&sheet.kind==='editor'&&e.target.name){const d=draft();d[e.target.name]=e.target.type==='checkbox'?e.target.checked:e.target.value;save();}});
  root.addEventListener('change',function(e){if(e.target.id==='pn-import-file'){importJSON(e.target.files[0]);e.target.value='';return;}if(e.target.dataset.task){const t=state.tasks.find(function(t){return t.id===e.target.dataset.task;});if(!t)return;t.done=e.target.checked;let earned=false;if(t.done&&!t.rewarded){t.rewarded=true;if(state.reward.tasks<5){state.reward.tasks++;award(5,'完成：'+t.title);earned=true;}state.round.task=true;}if(t.done){toast(earned?'小白给你盖了小爪印！ +5 狗狗币':'小白：这件小事完成啦！');}else toast('已撤销完成，任务保留');save();render();}else if(sheet&&sheet.kind==='editor'&&e.target.name){draft()[e.target.name]=e.target.type==='checkbox'?e.target.checked:e.target.value;save();}});
  function submitForm(e){e.preventDefault();const data=new FormData(e.target);
    if(e.target.id==='pn-note-form'){const d=draft();d.title=String(data.get('title')||'').trim();d.body=String(data.get('body')||'').trim();d.date=String(data.get('date')||TODAY);d.mood=String(data.get('mood'));d.diary=data.has('diary');if(!d.title&&!d.body&&!d.photo&&!d.audio){formError='先留下一点文字、照片或语音吧。';renderSheet();return;}if(recordTimer){clearInterval(recordTimer);recordTimer=null;d.recording=false;d.audio=true;}let n=state.notes.find(function(n){return n.id===d.id;});const isNew=!n;if(!n){n={id:'n'+Date.now(),rewarded:false,favorite:false};state.notes.unshift(n);}Object.assign(n,{title:d.title||'今天的一件小事',body:d.body,date:d.date,mood:d.mood,diary:d.diary,photo:d.photo,audio:d.audio,tag:d.diary?'日记':'生活'});let rewarded=false;if(isNew&&!n.rewarded){n.rewarded=true;if(state.reward.notes<3){award(3,'收好一页：'+n.title);state.reward.notes++;rewarded=true;}state.round.note=true;}state.draft=null;sheet=null;returnSheet=null;state.page='notes';state.noteFilter='all';save();render();toast(rewarded?'小鸡毛收好了这页！ +3 狗狗币':'这一页已经收好啦。');}
    else if(e.target.id==='pn-task-form'){const title=String(data.get('title')||'').trim();if(!title){formError='给这个小目标起个名字吧。';renderSheet();return;}let t=state.tasks.find(function(t){return t.id===sheet.id;});if(!t){t={id:'t'+Date.now(),done:false,rewarded:false};state.tasks.push(t);}Object.assign(t,{title:title,date:String(data.get('date')||''),time:String(data.get('time')||'')});sheet=null;state.page='tasks';state.taskFilter='all';save();render();toast('小目标已记好。');}
    else if(e.target.id==='pn-extract-form'){let count=0;draftTasks.forEach(function(t,i){if(data.has('pick'+i)){state.tasks.push({id:'t'+Date.now()+'-'+i,title:String(data.get('title'+i)||t.title).trim(),date:String(data.get('date'+i)||TODAY),time:'',done:false,rewarded:false});count++;}});sheet=null;returnSheet=null;state.page='tasks';state.taskFilter='all';save();render();toast(count?'已加入 '+count+' 个小目标':'没有加入任务，草稿已关闭。');}
    else if(e.target.id==='pn-chat-form')chatSend(String(data.get('message')||''));
    else if(e.target.id==='pn-anniversary-form'){const title=String(data.get('title')||'').trim(),date=String(data.get('date')||'');if(!title||!date){formError='请填写名称和日期。';renderSheet();return;}state.anniversaries.push({id:'a'+Date.now(),title:title,date:date,annual:data.has('annual')});save();openSheet('anniversaries');toast('重要的日子已记好。');}
  }
  root.addEventListener('submit',submitForm);
  root.addEventListener('click',function(e){const b=e.target.closest('button[data-action]');if(!b||!root.contains(b)||b.disabled)return;const a=b.dataset.action;
    if(a==='submit-form'){e.preventDefault();submitForm({target:b.closest('form'),preventDefault:function(){}});}
    else if(a==='nav'){sheet=null;returnSheet=null;state.page=b.dataset.page;save();render();}
    else if(a==='close-sheet')closeSheet();
    else if(a==='new-note'){draft();openSheet('editor');}
    else if(a==='view-note')openSheet('note',b.dataset.id);
    else if(a==='edit-note'){const n=state.notes.find(function(n){return n.id===b.dataset.id;});state.draft=Object.assign({},n,{recording:false});openSheet('editor');}
    else if(a==='favorite'){const n=state.notes.find(function(n){return n.id===b.dataset.id;});n.favorite=!n.favorite;save();render();toast(n.favorite?'已放进收藏':'已取消收藏');}
    else if(a==='note-filter'){state.noteFilter=b.dataset.value;save();render();}
    else if(a==='task-filter'){state.taskFilter=b.dataset.value;save();render();}
    else if(a==='new-task')openSheet('task');
    else if(a==='edit-task')openSheet('task',b.dataset.id);
    else if(a==='toggle-photo'){draft().photo=!draft().photo;save();renderSheet();toast(draft().photo?'示例照片已贴好':'已移除照片');}
    else if(a==='voice'){const d=draft();if(d.recording){clearInterval(recordTimer);recordTimer=null;d.recording=false;d.audio=true;save();renderSheet();toast('模拟语音已保留，可以回听。');}else{d.recording=true;recordSeconds=0;renderSheet();recordTimer=setInterval(function(){recordSeconds++;const t=root.querySelector('#pn-recordtime');if(t)t.textContent='录制中 '+recordSeconds+'秒';},1000);toast('正在模拟录音，无需开启麦克风。');}}
    else if(a==='audio-play')toast('模拟回听：周六带豆豆去洗澡，顺便买狗粮。');
    else if(a==='extract'){const n=state.notes.find(function(n){return n.id===b.dataset.id;});extract(n?n.body:draft().body);}
    else if(a==='extract-chat'){const m=state.chats[state.pet].slice().reverse().find(function(m){return m.role==='user';});extract(m?m.text:'周六带豆豆去洗澡，顺便买狗粮。');}
    else if(a==='shop'){shopTab='food';openSheet('shop');}
    else if(a==='shop-tab'){shopTab=b.dataset.value;formError='';renderSheet();}
    else if(a==='buy'){const k=b.dataset.key,p=products[k];if(state.coins<p.price){formError='还差 '+(p.price-state.coins)+' 狗狗币，记一笔或完成小目标就能攒到。';renderSheet();return;}if(p.type!=='food'&&state.bag[k])return;state.coins-=p.price;if(p.type==='food'){state.bag[k]++;state.round.buy=true;}else state.bag[k]=true;state.ledger.push({text:'购买：'+p.name,amount:-p.price});formError='';save();render();toast(p.name+'已放进背包。');}
    else if(a==='bag')openSheet('bag');
    else if(a==='feed-menu')openSheet('feed');
    else if(a==='free-food'){if(state.freeFood)return;state.freeFood=true;state.bag.food++;save();renderSheet();toast('领到一份基础口粮。');}
    else if(a==='feed')interact('feed',b.dataset.key);
    else if(a==='pet'||a==='play'||a==='rest'){if(sheet){sheet=null;returnSheet=null;state.page='home';}interact(a,b.dataset.toy);}
    else if(a==='select-pet'){state.pet=b.dataset.pet;petPose='defaultQuiet';petPhrase='今天想一起做什么？';clearTimeout(poseTimer);save();render();}
    else if(a==='companion'){state.pet=b.dataset.pet;save();openSheet('chat');}
    else if(a==='decorate')openSheet('decorate');
    else if(a==='equip'){state.decor[state.pet]=b.dataset.key;sheet=null;state.page='home';save();render();toast('小窝布置好啦。');}
    else if(a==='chat')openSheet('chat');
    else if(a==='chat-preset')chatSend(b.dataset.text);
    else if(a==='round')openSheet('round');
    else if(a==='round-go'){state.page=b.dataset.page;sheet=null;returnSheet=null;render();if(b.dataset.step==='buy')openSheet('shop');if(b.dataset.step==='feed')openSheet('feed');}
    else if(a==='wallet')openSheet('wallet');
    else if(a==='settings')openSheet('settings');
    else if(a==='export-svg'){sheet=null;returnSheet=null;render();if(typeof window.puppyExportSVG==='function'){exportSource=window.puppyExportSVG(phone,'小狗记事本.svg',{download:false,title:'小狗记事本 · '+({notes:'随手记',tasks:'待办',home:'小窝'}[state.page])});openSheet('export');}}
    else if(a==='export-json')exportJSON();
    else if(a==='import-json'){const f=root.querySelector('#pn-import-file');if(f)f.click();}
    else if(a==='reset'){clearInterval(recordTimer);clearTimeout(poseTimer);recordTimer=null;state=seed();sheet=null;returnSheet=null;petPose='defaultQuiet';petPhrase='今天想一起做什么？';save();render();toast('虚构演示已重置。');}
    else if(a==='anniversaries')openSheet('anniversaries');
    else if(a==='new-anniversary')openSheet('new-anniversary');
    else if(a==='anniversary-note'){state.draft={id:null,title:b.dataset.title+'的一页',body:'',date:TODAY,mood:'期待',diary:true,photo:false,audio:false,recording:false};openSheet('editor');}
    else if(a==='calendar')openSheet('calendar');
    else if(a==='calendar-day'){state.calendarDate=b.dataset.date;renderSheet();}
    else if(a==='search'){searchQuery='';openSheet('search');}
  });
  root.addEventListener('keydown',function(e){if(e.key==='Escape'&&sheet){e.preventDefault();closeSheet();}else if(e.key==='Enter'&&e.target.tagName==='INPUT'&&e.target.closest('form')){e.preventDefault();submitForm({target:e.target.closest('form'),preventDefault:function(){}});}});
})();
